# Platform specific code base information is applied here
if(MSVC)
 include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/Platform/Windows)
 include_directories(SYSTEM ${CMAKE_CURRENT_SOURCE_DIR}/src/platform/msc)
elseif(APPLE)
 include_directories(SYSTEM /usr/include/malloc)
 enable_language(ASM)
 include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/Platform/OSX)
 include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/Platform/Posix)
else()
 include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/Platform/Linux)
 include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/Platform/Posix)
endif()