## This section helps us tag our builds with the git commit information
set(versionScript "${CMAKE_CURRENT_LIST_DIR}/VersionScript.cmake")
set(AMITY_VERSION_INPUT_FILE "${CMAKE_SOURCE_DIR}/VERSION")
set(AMITY_VERSION_INCLUDE_DIR "${CMAKE_BINARY_DIR}/version")
set(AMITY_VERSION_TEMPLATE "${CMAKE_CURRENT_SOURCE_DIR}/src/config/version.h.in")
set(AMITY_VERSION_FILE "${AMITY_VERSION_INCLUDE_DIR}/version.h")
file(MAKE_DIRECTORY ${AMITY_VERSION_INCLUDE_DIR})
add_custom_target(
    version
    COMMAND ${CMAKE_COMMAND}
        -DCMAKE_SOURCE_DIR=${CMAKE_SOURCE_DIR}
        -DAMITY_VERSION_INPUT_FILE=${AMITY_VERSION_INPUT_FILE}
        -DAMITY_VERSION_TEMPLATE=${AMITY_VERSION_TEMPLATE}
        -DAMITY_VERSION_INCLUDE_DIR=${AMITY_VERSION_INCLUDE_DIR}
        -P ${versionScript}
    BYPRODUCT ${AMITY_VERSION_FILE}
    COMMENT "Updating version information..."
    SOURCES ${AMITY_VERSION_TEMPLATE} ${AMITY_VERSION_INPUT_FILE} ${versionScript}
)
